#!/bin/bash

if [ ! $(command -v singularity) ]; then
	module load singularity
fi

VERSION=1.2.10
PACKAGE=velvet
TOOL=velveth
DIRECTORY=$PWDHERE/software/Velvet
STORAGE=/N/home/,/N/slate,/N/project

OPTIONS=$OPTIONS" -B $STORAGE"

singularity exec $OPTIONS $DIRECTORY/singularity-$PACKAGE-$VERSION.sif $TOOL "$@"
